aws-iot-device-client: upgrade 1.9.13 -> 1.10.0, re-enable simple ptest
(cherry picked from commit 706a00fc301cfe489b34033cb9aa63b30e5e8771)

diff --git a/recipes-iot/aws-iot-device-client/files/run-ptest b/recipes-iot/aws-iot-device-client/files/run-ptest
--- a/recipes-iot/aws-iot-device-client/files/run-ptest
+++ b/recipes-iot/aws-iot-device-client/files/run-ptest
@@ -1,6 +1,11 @@
 #!/bin/sh
-# Copyright (c) 2022 Amazon.com, Inc. or its affiliates.
-# SPDX-License-Identifier: MIT
+export LD_PRELOAD=$(find /usr/lib /lib -type f -name "libasan.so*")
 
-./test-aws-iot-device-client --gtest_output=json:result.json
-python3 ptest_result.py result.json 
+aws-iot-device-client --help
+
+RETVAL=$?
+if [ $RETVAL -eq 0 ] ; then
+    echo "PASS: aws-iot-device-client: simple test"
+else
+    echo "FAIL: aws-iot-device-client: simple test"
+fi
