aws-iot-fleetwise, amazon-s3-gst-plugin, aws-crt-cpp, aws-iot-device-sdk-cpp-v2,s2n: improve tests
(cherry picked from commit 6dae05651fd5329f12b01b02249556bdf6ee5d26)

diff --git a/recipes-iot/aws-iot-fleetwise/files/run-ptest b/recipes-iot/aws-iot-fleetwise/files/run-ptest
--- a/recipes-iot/aws-iot-fleetwise/files/run-ptest
+++ b/recipes-iot/aws-iot-fleetwise/files/run-ptest
@@ -10,3 +10,34 @@ if [ $RETVAL -eq 0 ] ; then
 else
     echo "FAIL: aws-iot-fleetwise startup test"
 fi
+
+### fwe-gtest
+tests/fwe-gtest --gtest_filter=\
+-AwsIotConnectivityModuleTest*:\
+-CANDecoderTest*:\
+-CANDataSourceTest.*:\
+-CollectionInspectionEngine*:\
+-CollectionInspectionWorkerThreadTest.*:\
+-IoTFleetWiseConfigTest.ReadOk:\
+-IoTFleetWiseEngineTest.*:\
+-CollectionInspectionEngineDoubleTest.RandomDataTest\
+-ISOTPOverCANProtocolTest.*:\
+-OBDOverCANModuleTest.* \
+--gtest_fail_fast --gtest_output=json:result.json > /dev/null ;  python3 ptest_result.py result.json 
+
+
+### fwe-benchmark
+cd tests
+
+rm -rf tests.log
+
+./fwe-benchmark >> tests.log 2>&1
+
+RETVAL=$?
+sed  -e '/\[\s\|==.*==\|runtime error:/!d ; /OK/ s/^/PASS: / ; /FAILED\|ERROR: .*Sanitizer\|runtime error:/ s/^/FAIL: /'  tests.log
+
+if [ $RETVAL -eq 0 ] ; then
+    echo "PASS: fwe-benchmark test"
+else
+    echo "FAIL: fwe-benchmark test"
+fi
